import { TetQuestion, TetTest, TetTestWithQuestions } from './tetTestService';

export const PAPER_1A_TEST_ID = 'c97f31ea-1125-4ff7-84bc-d9e52f2c3803';

export const PAPER_1A_TEST: TetTest = {
  id: PAPER_1A_TEST_ID,
  title: 'Special APTET Paper 1A Mock Test 01',
  description: 'Verified 120-question authentic mock examination for Special APTET Paper 1A (Classes I-V).',
  test_type: 'PAPER_1A_MOCK',
  duration_minutes: 150,
  total_questions: 120,
  created_at: '2026-10-05T12:00:00.000Z',
};

// 120 Verified Questions:
// 1 - 30: Child Development & Pedagogy (Special Education) (30)
// 31 - 60: Mathematics (30)
// 61 - 90: Language I (Telugu) (30)
// 91 - 120: Language II (English) (30)

const cdpQuestions: TetQuestion[] = [
  {
    question_id: 1001,
    subject: 'Child Development & Pedagogy',
    question_number: 1,
    question_order: 1,
    question: 'The principle that states "An individual starting his life from a single fertilized cell develops through continuous differentiation into a complex organism" illustrates which principle of development?',
    option_a: 'Principle of Interrelation (పరస్పర సంబంధ సూత్రం)',
    option_b: 'Principle of Continuity (నిరంతర వికాస సూత్రం)',
    option_c: 'Principle of Differentiation and Integration (విభేదీకరణ మరియు సమగ్రతా సూత్రం)',
    option_d: 'Principle of Uniform Pattern (క్రమానుగత సూత్రం)',
    correct_option: 3,
  },
  {
    question_id: 1002,
    subject: 'Child Development & Pedagogy',
    question_number: 2,
    question_order: 2,
    question: 'According to Jean Piaget, during which cognitive stage does a child develop object permanence and begin to understand cause-effect relationships through sensory exploration?',
    option_a: 'Sensorimotor Stage (ఇంద్రియ ప్రచాలక దశ: 0-2 yrs)',
    option_b: 'Pre-operational Stage (పూర్వ ప్రచాలక దశ: 2-7 yrs)',
    option_c: 'Concrete Operational Stage (మూర్త ప్రచాలక దశ: 7-11 yrs)',
    option_d: 'Formal Operational Stage (అమూర్త ప్రచాలక దశ: 11+ yrs)',
    correct_option: 1,
  },
  {
    question_id: 1003,
    subject: 'Child Development & Pedagogy',
    question_number: 3,
    question_order: 3,
    question: 'In Lev Vygotsky\'s sociocultural theory, the assistance and temporary support provided by a More Knowledgeable Other (MKO) to help a learner master a task is called:',
    option_a: 'Assimilation (సాంశీకరణం)',
    option_b: 'Scaffolding (స్క్యాఫోల్డింగ్ / ఆసరా కల్పించడం)',
    option_c: 'Equilibration (సమతుల్యత)',
    option_d: 'Conservation (సంరక్షణ భావన)',
    correct_option: 2,
  },
  {
    question_id: 1004,
    subject: 'Child Development & Pedagogy',
    question_number: 4,
    question_order: 4,
    question: 'According to Lawrence Kohlberg, at which level of moral development do children conform to social rules primarily to gain approval and maintain good interpersonal relationships?',
    option_a: 'Pre-conventional Level (పూర్వ సాంప్రదాయక స్థాయి)',
    option_b: 'Conventional Level (సాంప్రదాయక స్థాయి - Good Boy/Nice Girl)',
    option_c: 'Post-conventional Level (ఉత్తర సాంప్రదాయక స్థాయి)',
    option_d: 'Universal Ethical Principle Level (సార్వత్రిక నైతిక సూత్రాల స్థాయి)',
    correct_option: 2,
  },
  {
    question_id: 1005,
    subject: 'Child Development & Pedagogy',
    question_number: 5,
    question_order: 5,
    question: 'According to Howard Gardner\'s Theory of Multiple Intelligences, a child who excels in understanding other people\'s emotions, motivations, and intentions exhibits:',
    option_a: 'Intrapersonal Intelligence (వ్యక్తి అంతర్గత ప్రజ్ఞ)',
    option_b: 'Interpersonal Intelligence (వ్యక్తి అంతర ప్రజ్ఞ)',
    option_c: 'Spatial Intelligence (దృశ్య-ప్రాదేశిక ప్రజ్ఞ)',
    option_d: 'Linguistic Intelligence (భాషా ప్రజ్ఞ)',
    correct_option: 2,
  },
  {
    question_id: 1006,
    subject: 'Child Development & Pedagogy',
    question_number: 6,
    question_order: 6,
    question: 'Which of the following is the most inclusive characteristic of an "Inclusive Classroom" (సమ్మిళిత తరగతి గది)?',
    option_a: 'Grouping children with disabilities in a separate section of the room',
    option_b: 'Providing equal opportunities and differentiated instruction for all learners regardless of physical or cognitive differences',
    option_c: 'Only admitting gifted learners and standard students',
    option_d: 'Exempting children with special needs from examination curricula entirely',
    correct_option: 2,
  },
  {
    question_id: 1007,
    subject: 'Child Development & Pedagogy',
    question_number: 7,
    question_order: 7,
    question: 'An Individualized Education Plan (IEP / వ్యక్తిగత విద్యా ప్రణాళిక) for a child with special needs must primarily include:',
    option_a: 'Only the medical history without educational milestones',
    option_b: 'Current performance level, measurable annual goals, and specific accommodations',
    option_c: 'A standardized punishment procedure for non-compliance',
    option_d: 'Only extra-curricular guidelines without academic modifications',
    correct_option: 2,
  },
  {
    question_id: 1008,
    subject: 'Child Development & Pedagogy',
    question_number: 8,
    question_order: 8,
    question: 'Dyslexia (డిస్లెక్సియా) is predominantly associated with difficulty in:',
    option_a: 'Mathematical operations and arithmetic calculation',
    option_b: 'Reading fluency, decoding words, and phonological processing',
    option_c: 'Motor coordination and balance',
    option_d: 'Social communication and repetitive behaviors',
    correct_option: 2,
  },
  {
    question_id: 1009,
    subject: 'Child Development & Pedagogy',
    question_number: 9,
    question_order: 9,
    question: 'Dyscalculia (డిస్కాల్క్యులియా) in primary school children refers to a specific learning disability affecting:',
    option_a: 'Handwriting legibility and fine motor skills',
    option_b: 'Language comprehension in auditory speech',
    option_c: 'Mathematical concepts, numbers sense, and arithmetic calculations',
    option_d: 'Vision alignment and eye-hand coordination',
    correct_option: 3,
  },
  {
    question_id: 1010,
    subject: 'Child Development & Pedagogy',
    question_number: 10,
    question_order: 10,
    question: 'Under the Rights of Persons with Disabilities (RPwD) Act, 2016, how many benchmark disabilities are recognized in India?',
    option_a: '7 disabilities',
    option_b: '14 disabilities',
    option_c: '21 disabilities',
    option_d: '28 disabilities',
    correct_option: 3,
  },
  {
    question_id: 1011,
    subject: 'Child Development & Pedagogy',
    question_number: 11,
    question_order: 11,
    question: 'Which pedagogical accommodation is most beneficial for a student with Attention Deficit Hyperactivity Disorder (ADHD)?',
    option_a: 'Giving long, continuous lectures without breaks',
    option_b: 'Breaking tasks into small manageable chunks with frequent positive reinforcement',
    option_c: 'Isolating the student in a corner away from peers',
    option_d: 'Relying exclusively on written examinations without oral alternatives',
    correct_option: 2,
  },
  {
    question_id: 1012,
    subject: 'Child Development & Pedagogy',
    question_number: 12,
    question_order: 12,
    question: 'The cephalocaudal principle of motor development states that development proceeds from:',
    option_a: 'Center of the body outwards to extremities',
    option_b: 'Head downwards to feet (శిరోపాద ధోరణి)',
    option_c: 'Simple reflex actions to abstract logic',
    option_d: 'General motor responses to specific sensory actions only',
    correct_option: 2,
  },
  {
    question_id: 1013,
    subject: 'Child Development & Pedagogy',
    question_number: 13,
    question_order: 13,
    question: 'The proximodistal principle of development dictates that physical growth proceeds from:',
    option_a: 'Head to toes',
    option_b: 'Near to far (from central core of the body outward to fingers/extremities)',
    option_c: 'Hands to chest',
    option_d: 'Feet towards spinal cord',
    correct_option: 2,
  },
  {
    question_id: 1014,
    subject: 'Child Development & Pedagogy',
    question_number: 14,
    question_order: 14,
    question: 'In the context of Special Education, Universal Design for Learning (UDL) emphasizes:',
    option_a: 'One single uniform exam for all students regardless of ability',
    option_b: 'Multiple means of representation, engagement, and expression for diverse learners',
    option_c: 'Designing physical school buildings with single entrances only',
    option_d: 'Exclusively digital learning without human teacher interaction',
    correct_option: 2,
  },
  {
    question_id: 1015,
    subject: 'Child Development & Pedagogy',
    question_number: 15,
    question_order: 15,
    question: 'According to B.F. Skinner\'s Operant Conditioning, which reinforcement schedule is most resistant to extinction?',
    option_a: 'Continuous reinforcement',
    option_b: 'Fixed-interval reinforcement',
    option_c: 'Variable-ratio reinforcement (మార్పుగల నిష్పత్తి పునర్బలనం)',
    option_d: 'Fixed-ratio reinforcement',
    correct_option: 3,
  },
  {
    question_id: 1016,
    subject: 'Child Development & Pedagogy',
    question_number: 16,
    question_order: 16,
    question: 'In Ivan Pavlov\'s Classical Conditioning experiment with dogs, the sound of the bell before conditioning was the:',
    option_a: 'Unconditioned Stimulus (సహజ ఉద్దీపన)',
    option_b: 'Conditioned Response (నిబంధిత ప్రతిస్పందన)',
    option_c: 'Neutral Stimulus (తటస్థ ఉద్దీపన)',
    option_d: 'Unconditioned Response (సహజ ప్రతిస్పందన)',
    correct_option: 3,
  },
  {
    question_id: 1017,
    subject: 'Child Development & Pedagogy',
    question_number: 17,
    question_order: 17,
    question: 'Which of the following is a primary characteristic of Autism Spectrum Disorder (ASD)?',
    option_a: 'Superficial rapid speech without motor control',
    option_b: 'Impairments in reciprocal social interaction and restricted repetitive patterns of behavior',
    option_c: 'Profound muscular dystrophy in early infancy',
    option_d: 'Severe loss of peripheral vision only',
    correct_option: 2,
  },
  {
    question_id: 1018,
    subject: 'Child Development & Pedagogy',
    question_number: 18,
    question_order: 18,
    question: 'Formative Assessment (నిర్మాణాత్మక మూల్యాంకనం) in school education is best described as assessment that:',
    option_a: 'Occurs only at the end of the academic year for grading and promotion',
    option_b: 'Provides continuous diagnostic feedback during the learning process to improve instruction',
    option_c: 'Ranks students against national percentiles solely',
    option_d: 'Measures only factual memorization through external proctored boards',
    correct_option: 2,
  },
  {
    question_id: 1019,
    subject: 'Child Development & Pedagogy',
    question_number: 19,
    question_order: 19,
    question: 'According to Erik Erikson\'s Psychosocial theory, the primary crisis faced by children during the elementary school years (6-12 years) is:',
    option_a: 'Trust vs. Mistrust (నమ్మకం - అపనమ్మకం)',
    option_b: 'Autonomy vs. Shame and Doubt (స్వయంప్రతిపత్తి - సందేహం)',
    option_c: 'Industry vs. Inferiority (శ్రమశీలత - న్యూనత)',
    option_d: 'Identity vs. Role Confusion (గుర్తింపు - పాత్ర సందిగ్ధత)',
    correct_option: 3,
  },
  {
    question_id: 1020,
    subject: 'Child Development & Pedagogy',
    question_number: 20,
    question_order: 20,
    question: 'What is the standard IQ range classified as "Average Intelligence" according to Wechsler and Stanford-Binet scales?',
    option_a: '70 - 79',
    option_b: '90 - 109',
    option_c: '120 - 129',
    option_d: '130 - 139',
    correct_option: 2,
  },
  {
    question_id: 1021,
    subject: 'Child Development & Pedagogy',
    question_number: 21,
    question_order: 21,
    question: 'Which of the following teaching aids is indispensable for teaching geometric concepts to visually impaired students?',
    option_a: 'Standard blackboard diagrams with chalk',
    option_b: 'Taylor frame and tactile geometry kit with raised relief lines',
    option_c: 'High-speed silent projection videos',
    option_d: 'Silent reading textbook assignments',
    correct_option: 2,
  },
  {
    question_id: 1022,
    subject: 'Child Development & Pedagogy',
    question_number: 22,
    question_order: 22,
    question: 'The Zone of Proximal Development (ZPD / సామీప్య వికాస రంగం) is defined by Vygotsky as the distance between:',
    option_a: 'Biological age and chronological age',
    option_b: 'Actual developmental level and potential developmental level determined with guidance',
    option_c: 'Physical strength and cognitive memory retention',
    option_d: 'Home vocabulary and school literacy performance',
    correct_option: 2,
  },
  {
    question_id: 1023,
    subject: 'Child Development & Pedagogy',
    question_number: 23,
    question_order: 23,
    question: 'Dysgraphia (డిస్గ్రాఫియా) is a specific learning disorder that impairs a child\'s:',
    option_a: 'Ability to listen to auditory cues',
    option_b: 'Writing mechanics, handwriting legibility, and fine motor finger spelling',
    option_c: 'Balance while jumping or running',
    option_d: 'Visual color recognition',
    correct_option: 2,
  },
  {
    question_id: 1024,
    subject: 'Child Development & Pedagogy',
    question_number: 24,
    question_order: 24,
    question: 'Which educational board/council is statutory in India for regulating training policies and programmes for personnel in the field of disability rehabilitation and special education?',
    option_a: 'NCTE (National Council for Teacher Education)',
    option_b: 'RCI (Rehabilitation Council of India / భారత పునరావాస మండలి)',
    option_c: 'NCERT (National Council of Educational Research and Training)',
    option_d: 'AICTE (All India Council for Technical Education)',
    correct_option: 2,
  },
  {
    question_id: 1025,
    subject: 'Child Development & Pedagogy',
    question_number: 25,
    question_order: 25,
    question: 'According to Maslow\'s Hierarchy of Needs, which level represents the most fundamental physiological necessity before higher learning can occur effectively?',
    option_a: 'Self-Actualization needs',
    option_b: 'Esteem needs',
    option_c: 'Safety and Survival needs (ఆహారం, నీరు, నివాసం మరియు భద్రత)',
    option_d: 'Cognitive aesthetic needs',
    correct_option: 3,
  },
  {
    question_id: 1026,
    subject: 'Child Development & Pedagogy',
    question_number: 26,
    question_order: 26,
    question: 'Continuous and Comprehensive Evaluation (CCE) aims to assess:',
    option_a: 'Scholastic areas only through pen-paper tests',
    option_b: 'Both scholastic and co-scholastic domains of a learner\'s personality comprehensively',
    option_c: 'Only sports participation and attendance rates',
    option_d: 'Teacher punctuality and syllabus coverage speeds',
    correct_option: 2,
  },
  {
    question_id: 1027,
    subject: 'Child Development & Pedagogy',
    question_number: 27,
    question_order: 27,
    question: 'A teacher notices that a student frequently holds reading material extremely close to the eyes, squinting and complaining of headaches. The teacher should first recommend:',
    option_a: 'Immediate disciplinary detention for laziness',
    option_b: 'A professional pediatric visual acuity screening and ophthalmological checkup',
    option_c: 'Exempting the child from all classroom instruction',
    option_d: 'Changing the student\'s native speaking language',
    correct_option: 2,
  },
  {
    question_id: 1028,
    subject: 'Child Development & Pedagogy',
    question_number: 28,
    question_order: 28,
    question: 'The primary difference between "Growth" (పెరుగుదల) and "Development" (వికాసం) is:',
    option_a: 'Growth is qualitative while Development is purely quantitative',
    option_b: 'Growth is quantitative and cellular while Development is progressive, qualitative and continuous throughout life',
    option_c: 'Growth continues until old age while Development stops at adolescence',
    option_d: 'Growth and development are completely synonymous in child psychology',
    correct_option: 2,
  },
  {
    question_id: 1029,
    subject: 'Child Development & Pedagogy',
    question_number: 29,
    question_order: 29,
    question: 'In an inclusive classroom, differentiated instruction means:',
    option_a: 'Teaching every student the exact same sentence at the exact same pace',
    option_b: 'Tailoring content, process, and products according to students\' varying readiness levels and learning profiles',
    option_c: 'Separating low scoring students into a basement room',
    option_d: 'Eliminating the syllabus entirely for standard learners',
    correct_option: 2,
  },
  {
    question_id: 1030,
    subject: 'Child Development & Pedagogy',
    question_number: 30,
    question_order: 30,
    question: 'The National Education Policy (NEP) 2020 replaces the 10+2 curricular structure with which pedagogical structure?',
    option_a: '5 + 3 + 3 + 4 (ఫౌండేషనల్, ప్రిపరేటరీ, మిడిల్, సెకండరీ)',
    option_b: '4 + 4 + 4 + 2',
    option_c: '3 + 3 + 4 + 5',
    option_d: '5 + 4 + 3 + 2',
    correct_option: 1,
  },
];

const mathQuestions: TetQuestion[] = Array.from({ length: 30 }, (_, i) => {
  const qNum = i + 1;
  const order = 30 + qNum;
  const qId = 2000 + qNum;

  const data: Array<{
    q: string;
    a: string;
    b: string;
    c: string;
    d: string;
    ans: number;
  }> = [
    {
      q: 'The place value of 7 in the number 47,825 is:',
      a: '70',
      b: '700',
      c: '7,000 (ఏడు వేలు)',
      d: '70,000',
      ans: 3,
    },
    {
      q: 'The difference between the place value and face value of 6 in 9,642 is:',
      a: '594 (600 - 6 = 594)',
      b: '600',
      c: '6',
      d: '540',
      ans: 1,
    },
    {
      q: 'What is the smallest prime number (అతి చిన్న ప్రధాన సంఖ్య)?',
      a: '0',
      b: '1',
      c: '2',
      d: '3',
      ans: 3,
    },
    {
      q: 'The HCF of 24 and 36 is:',
      a: '6',
      b: '8',
      c: '12 (గాసాభా = 12)',
      d: '72',
      ans: 3,
    },
    {
      q: 'The LCM of 12, 15 and 20 is:',
      a: '30',
      b: '60 (కసాగు = 60)',
      c: '120',
      d: '180',
      ans: 2,
    },
    {
      q: 'The sum of all interior angles of a quadrilateral (చతుర్భుజంలోని కోణాల మొత్తం) is:',
      a: '180°',
      b: '270°',
      c: '360°',
      d: '540°',
      ans: 3,
    },
    {
      q: 'If the side of a square is 12 cm, its perimeter and area are respectively:',
      a: '24 cm and 144 cm²',
      b: '48 cm and 144 cm²',
      c: '48 cm and 24 cm²',
      d: '36 cm and 72 cm²',
      ans: 2,
    },
    {
      q: 'Which of the following fractions is equivalent to 3/4?',
      a: '6/12',
      b: '9/12',
      c: '12/20',
      d: '15/24',
      ans: 2,
    },
    {
      q: 'Evaluate: 3/5 + 1/4 = ?',
      a: '4/9',
      b: '17/20',
      c: '7/20',
      d: '13/20',
      ans: 2,
    },
    {
      q: 'If 15 pens cost ₹225, what is the cost of 8 such pens?',
      a: '₹120 (ఒక్కటి ₹15, 8 pens = ₹120)',
      b: '₹110',
      c: '₹125',
      d: '₹135',
      ans: 1,
    },
    {
      q: 'Express 0.375 as a fraction in simplest form:',
      a: '3/8',
      b: '5/8',
      c: '7/16',
      d: '1/3',
      ans: 1,
    },
    {
      q: 'The average of numbers 14, 18, 22, 26, and 30 is:',
      a: '20',
      b: '22',
      c: '24',
      d: '26',
      ans: 2,
    },
    {
      q: 'What is 25% of 480?',
      a: '100',
      b: '120 (480 / 4 = 120)',
      c: '140',
      d: '160',
      ans: 2,
    },
    {
      q: 'If an article bought for ₹400 is sold for ₹480, the profit percentage is:',
      a: '15%',
      b: '20% ((80 / 400) * 100 = 20%)',
      c: '25%',
      d: '30%',
      ans: 2,
    },
    {
      q: 'Simple Interest on ₹5,000 at 6% per annum for 3 years is:',
      a: '₹600',
      b: '₹750',
      c: '₹900 ((5000 * 6 * 3) / 100 = 900)',
      d: '₹1,000',
      ans: 3,
    },
    {
      q: 'A train 150 meters long crosses a pole in 10 seconds. Its speed in km/h is:',
      a: '45 km/h',
      b: '54 km/h (15 m/s * 18/5 = 54 km/h)',
      c: '60 km/h',
      d: '72 km/h',
      ans: 2,
    },
    {
      q: 'The area of a triangle with base 14 cm and height 9 cm is:',
      a: '63 cm² (1/2 * 14 * 9 = 63)',
      b: '126 cm²',
      c: '46 cm²',
      d: '72 cm²',
      ans: 1,
    },
    {
      q: 'How many edges (అంచులు) does a standard cube possess?',
      a: '6',
      b: '8',
      c: '12',
      d: '16',
      ans: 3,
    },
    {
      q: 'The supplement of an angle measuring 65° is:',
      a: '25°',
      b: '115° (180° - 65° = 115°)',
      c: '125°',
      d: '135°',
      ans: 2,
    },
    {
      q: 'Which of the following is a pythagorean triplet (పైథాగరియన్ త్రికం)?',
      a: '3, 4, 6',
      b: '5, 12, 13 (5² + 12² = 13²)',
      c: '6, 8, 12',
      d: '7, 9, 11',
      ans: 2,
    },
    {
      q: 'In Roman numerals, the number 94 is written as:',
      a: 'LXXXXIV',
      b: 'XCIV (90 + 4 = XCIV)',
      c: 'CXIV',
      d: 'ICIV',
      ans: 2,
    },
    {
      q: 'The volume of a cuboid measuring 8 cm × 5 cm × 3 cm is:',
      a: '120 cm³ (8 * 5 * 3 = 120)',
      b: '140 cm³',
      c: '160 cm³',
      d: '240 cm³',
      ans: 1,
    },
    {
      q: 'A car covers 240 km in 4 hours. How long will it take to travel 450 km at the same speed?',
      a: '6.5 hours',
      b: '7.5 hours (speed = 60 km/h, 450 / 60 = 7.5)',
      c: '8 hours',
      d: '9 hours',
      ans: 2,
    },
    {
      q: 'The value of: 25 - 5 × 2 + 10 ÷ 2 is:',
      a: '20 (BODMAS: 25 - 10 + 5 = 20)',
      b: '25',
      c: '15',
      d: '30',
      ans: 1,
    },
    {
      q: 'Convert 3.5 kilograms into grams:',
      a: '350 grams',
      b: '3,500 grams',
      c: '35,000 grams',
      d: '35 grams',
      ans: 2,
    },
    {
      q: 'A clock shows 3:30. What is the angle between the hour hand and minute hand?',
      a: '70°',
      b: '75° (|30*3 - 5.5*30| = |90 - 165| = 75°)',
      c: '80°',
      d: '85°',
      ans: 2,
    },
    {
      q: 'Which of the following numbers is divisible by both 3 and 4?',
      a: '154',
      b: '192 (1+9+2=12, last digits 92 divisible by 4)',
      c: '214',
      d: '226',
      ans: 2,
    },
    {
      q: 'In mathematics teaching, an Abacus (పూసల చట్రం) is particularly useful for teaching:',
      a: 'Geometric theorems and coordinate geometry',
      b: 'Place value, addition, and subtraction to visually impaired and primary students',
      c: 'Complex calculus derivatives',
      d: 'Trigonometric identities',
      ans: 2,
    },
    {
      q: 'The diameter of a circle is 28 cm. Its circumference (పరిధి) is (Take π = 22/7):',
      a: '44 cm',
      b: '88 cm (π * d = 22/7 * 28 = 88)',
      c: '176 cm',
      d: '616 cm',
      ans: 2,
    },
    {
      q: 'The probability of rolling an even number on a fair standard 6-sided dice is:',
      a: '1/6',
      b: '1/3',
      c: '1/2 (3/6 = 1/2)',
      d: '2/3',
      ans: 3,
    },
  ];

  const item = data[i];
  return {
    question_id: qId,
    subject: 'Mathematics',
    question_number: qNum,
    question_order: order,
    question: item.q,
    option_a: item.a,
    option_b: item.b,
    option_c: item.c,
    option_d: item.d,
    correct_option: item.ans,
  };
});

const teluguQuestions: TetQuestion[] = Array.from({ length: 30 }, (_, i) => {
  const qNum = i + 1;
  const order = 60 + qNum;
  const qId = 3000 + qNum;

  const data: Array<{
    q: string;
    a: string;
    b: string;
    c: string;
    d: string;
    ans: number;
  }> = [
    {
      q: '‘విద్యాధనం’ అనే పదానికి సరైన విగ్రహవాక్యం ఏమిటి?',
      a: 'విద్య యొక్క ధనం',
      b: 'విద్య అనునది ధనం (రూపక సమాసం)',
      c: 'విద్య కొరకు ధనం',
      d: 'విద్యతో ధనం',
      ans: 2,
    },
    {
      q: '‘సూర్యోదయము’ అనే పదంలో ఉన్న సంధి ఏది?',
      a: 'సవర్ణదీర్ఘ సంధి',
      b: 'గుణ సంధి (సూర్య + ఉదయము = సూర్యోదయము)',
      c: 'వృద్ధి సంధి',
      d: 'యణాదేశ సంధి',
      ans: 2,
    },
    {
      q: '‘కన్ను’ అను పదానికి నానార్థాలు గుర్తించండి:',
      a: 'నేత్రము, బండికన్ను, చెరువు తూము',
      b: 'చెవి, ముక్కు, నాలుక',
      c: 'చేయి, పాదము, శిరస్సు',
      d: 'సూర్యుడు, చంద్రుడు, నక్షత్రం',
      ans: 1,
    },
    {
      q: '‘మిత్రుడు’ పదానికి పర్యాయపదాలు ఏవి?',
      a: 'శత్రువు, విరోధి',
      b: 'స్నేహితుడు, నెచ్చెలి, సఖుడు',
      c: 'గురువు, ఉపాధ్యాయుడు',
      d: 'సోదరుడు, తమ్ముడు',
      ans: 2,
    },
    {
      q: '‘రాముడు రావణుని సంహరించెను’ — ఇది ఏ రకమైన వాక్యం?',
      a: 'కర్మణి వాక్యం',
      b: 'కర్తరి వాక్యం',
      c: 'ప్రేరణార్థక వాక్యం',
      d: 'ఆశ్చర్యార్థక వాక్యం',
      ans: 2,
    },
    {
      q: '‘ఆలయము’ అనే పదానికి గల ప్రకృతి-వికృతులలో వికృతి పదం ఏది?',
      a: 'గుడి',
      b: 'నెలవు',
      c: 'ఆలెము (ఆలయము - ఆలెము)',
      d: 'మందిరం',
      ans: 3,
    },
    {
      q: 'ఉత్పలమాల వృత్త పద్య పాదంలో వచ్చే గణాలు ఏవి?',
      a: 'భ - ర - న - భ - భ - ర - వ (భరణభభరవ)',
      b: 'న - జ - భ - జ - జ - జ - ర',
      c: 'మ - స - జ - స - త - త - గ',
      d: 'స - భ - ర - న - మ - య - వ',
      ans: 1,
    },
    {
      q: 'చంపకమాల పద్యంలో ప్రతి పాదంలో ఉండే అక్షరాల సంఖ్య ఎంత?',
      a: '19',
      b: '20',
      c: '21 (నజభజజజర - 21 అక్షరాలు)',
      d: '22',
      ans: 3,
    },
    {
      q: 'భాషా నైపుణ్యాలలో సరైన క్రమం ఏది?',
      a: 'పఠనం - లేఖనం - శ్రవణం - భాషణం',
      b: 'శ్రవణం - భాషణం - పఠనం - లేఖనం (LSRW)',
      c: 'భాషణం - శ్రవణం - లేఖనం - పఠనం',
      d: 'లేఖనం - పఠనం - శ్రవణం - భాషణం',
      ans: 2,
    },
    {
      q: 'దృష్టి లోపం గల విద్యార్థులకు తెలుగు భాషా బోధనలో అత్యంత ప్రాముఖ్యమైన సాధనం ఏది?',
      a: 'ఫ్లాష్ కార్డులు',
      b: 'బ్రైలీ లిపి మరియు శ్రవణ పుస్తకాలు (ఆడియో బుక్స్)',
      c: 'మౌన పఠన చార్టులు',
      d: 'నల్లబల్లపై పెద్ద రాతలు',
      ans: 2,
    },
    {
      q: '‘గుర్రము స్వచ్ఛమైన గడ్డిని మేసింది’ — ఇందులో విశేషణం ఏది?',
      a: 'గుర్రము',
      b: 'స్వచ్ఛమైన (గుణ విశేషణం)',
      c: 'గడ్డిని',
      d: 'మేసింది',
      ans: 2,
    },
    {
      q: '‘అమ్మ కొడుకు కొరకు ఎదురుచూస్తున్నది’ — ఇక్కడ ‘కొరకు’ అనేది ఏ విభక్తి ప్రత్యయం?',
      a: 'ద్వితీయా విభక్తి',
      b: 'తృతీయా విభక్తి',
      c: 'చతుర్థీ విభక్తి (కొఱకున్, కై)',
      d: 'పంచమీ విభక్తి',
      ans: 3,
    },
    {
      q: '‘ఉపాధ్యాయుడు పాఠం బోధిస్తున్నాడు’ — ఇది ఏ కాలానికి చెందిన వాక్యం?',
      a: 'భూతకాలం',
      b: 'వర్తమాన కాలం',
      c: 'భవిష్యత్ కాలం',
      d: 'తద్ధర్మ కాలం',
      ans: 2,
    },
    {
      q: '‘చెక్కిలి’ అను పదానికి బహువచన రూపం ఏది?',
      a: 'చెక్కిలులు',
      b: 'చెక్కిళ్లు (చెక్కులు / చెక్కిళ్లు)',
      c: 'చెక్కిలములు',
      d: 'చెక్కిలు',
      ans: 2,
    },
    {
      q: '‘మహాభారతం’ తెలుగులో ఆంధ్రీకరించిన కవిత్రయంలో మొదటివారు ఎవరు?',
      a: 'తిక్కన',
      b: 'ఎర్రన',
      c: 'నన్నయ భట్టారకుడు',
      d: 'శ్రీనాథుడు',
      ans: 3,
    },
    {
      q: 'శతక పద్యాలకు ఉండవలసిన ముఖ్య లక్షణాలలో ఒకటి ఏది?',
      a: 'మకుట నియమం (ప్రతి పద్యం చివర మకుటం ఉండటం)',
      b: 'కథా నిరంతరత',
      c: 'వచన సంభాషణలు',
      d: 'కథానాయకుడి జనన వర్ణన',
      ans: 1,
    },
    {
      q: '‘ఉపమేయాన్ని ఉపమానంతో మనోహరంగా పోల్చి చెప్పడం’ ఏ అలంకారం?',
      a: 'రూపక అలంకారం',
      b: 'ఉపమా అలంకారం',
      c: 'ఉత్ప్రేక్ష అలంకారం',
      d: 'అతిశయోక్తి అలంకారం',
      ans: 2,
    },
    {
      q: '‘అనగననగ రాగమతిశయిల్లుచునుండు’ అనే వేమన పద్యం ఏ ఛందస్సులో ఉంది?',
      a: 'తేటగీతి',
      b: 'ఆటవెలది',
      c: 'సీస పద్యం',
      d: 'కందం',
      ans: 2,
    },
    {
      q: 'ప్రత్యేక అవసరాలు గల పిల్లల్లో వాగ్రూప లోపాలు (Speech Impairments) సరిచేయడానికి ఉపయోగపడే ప్రక్రియ:',
      a: 'శ్రవణ పరీక్ష మాత్రమే',
      b: 'స్పీచ్ థెరపీ (వాక్ చికిత్స) మరియు శబ్దోచ్చారణ సాధన',
      c: 'రాత పరీక్షల శిక్షణ',
      d: 'మౌన దీక్ష పాటించడం',
      ans: 2,
    },
    {
      q: '‘కష్టపడి పనిచేస్తే విజయం వస్తుంది’ — ఇది ఏ రకమైన వాక్యం?',
      a: 'సాధారణ వాక్యం',
      b: 'సంశ్లిష్ట వాక్యం (చేదర్థక సంశ్లిష్టం)',
      c: 'సంయుక్త వాక్యం',
      d: 'ప్రశ్నార్థక వాక్యం',
      ans: 2,
    },
    {
      q: 'తెలుగు వర్ణమాలలో ‘క, చ, ట, త, ప’ లను ఏమంటారు?',
      a: 'సరళములు',
      b: 'పరుషములు (కఠినంగా పలికేవి)',
      c: 'అనునాసికములు',
      d: 'ఊష్మములు',
      ans: 2,
    },
    {
      q: '‘గ, జ, డ, ద, బ’ లను ఏమని పిలుస్తారు?',
      a: 'పరుషములు',
      b: 'సరళములు (సులభంగా పలికేవి)',
      c: 'అంతస్థములు',
      d: 'మహాప్రాణములు',
      ans: 2,
    },
    {
      q: 'ముక్కు సహాయంతో ఉచ్చరించే అక్షరాలను ఏమంటారు?',
      a: 'ఊష్మములు',
      b: 'అనునాసికములు (ఙ, ఞ, ణ, న, మ)',
      c: 'అంతస్థములు',
      d: 'స్పర్శములు',
      ans: 2,
    },
    {
      q: '‘శ, ష, స, హ’ లను ఏమని పిలుస్తారు?',
      a: 'ఊష్మములు (గాలిని ఊది పలికేవి)',
      b: 'అంతస్థములు',
      c: 'సరళములు',
      d: 'పరుషములు',
      ans: 1,
    },
    {
      q: '‘య, ర, ల, వ’ లను ఏమంటారు?',
      a: 'అనునాసికములు',
      b: 'ఊష్మములు',
      c: 'అంతస్థములు',
      d: 'మహాప్రాణాలు',
      ans: 3,
    },
    {
      q: 'తెలుగులో హ్రస్వ అక్షరాలను పలకడానికి పట్టే కాలాన్ని ఏమంటారు?',
      a: 'క్షణము',
      b: 'మాత్ర (ఒక మాత్ర కాలం)',
      c: 'విరామము',
      d: 'లయ',
      ans: 2,
    },
    {
      q: '‘దశరథ తనయుడు’ అను పదంలో ఏ సమాసం ఉంది?',
      a: 'ద్విగు సమాసం',
      b: 'షష్ఠీ తత్పురుష సమాసం (దశరథుని యొక్క తనయుడు)',
      c: 'ద్వంద్వ సమాసం',
      d: 'బహువ్రీహి సమాసం',
      ans: 2,
    },
    {
      q: '‘ముక్కంటి’ అనగా మూడు కన్నులు గలవాడు (శివుడు) — ఇది ఏ సమాసం?',
      a: 'ద్విగు సమాసం',
      b: 'బహువ్రీహి సమాసం (అన్యపదార్థ ప్రధానం)',
      c: 'కర్మధారయ సమాసం',
      d: 'ద్వంద్వ సమాసం',
      ans: 2,
    },
    {
      q: 'ప్రాథమిక తరగతులలో తెలుగు భాషా బోధనకు అత్యుత్తమమైన బోధనా పద్ధతి ఏది?',
      a: 'ఉపన్యాస పద్ధతి',
      b: 'క్రీడా పద్ధతి మరియు కృత్యాధార పద్ధతి (Activity-based & Playway)',
      c: 'కంఠస్థ పద్ధతి',
      d: 'అనువాద పద్ధతి మాత్రమే',
      ans: 2,
    },
    {
      q: 'బోధనోపకరణాలు (TLM) తరగతి గదిలో వినియోగించడం వలన కలిగే ప్రయోజనం:',
      a: 'ఉపాధ్యాయుడి శ్రమను పూర్తిగా నివారించడం',
      b: 'అభ్యాసనం ఆసక్తికరంగా, మూర్తంగా మరియు శాశ్వతంగా మారడం',
      c: 'పరీక్షలు రాయకుండా పిల్లలను ఉత్తీర్ణులను చేయడం',
      d: 'విద్యార్థుల హోంవర్కును రద్దు చేయడం',
      ans: 2,
    },
  ];

  const item = data[i];
  return {
    question_id: qId,
    subject: 'Language I (Telugu)',
    question_number: qNum,
    question_order: order,
    question: item.q,
    option_a: item.a,
    option_b: item.b,
    option_c: item.c,
    option_d: item.d,
    correct_option: item.ans,
  };
});

const englishQuestions: TetQuestion[] = Array.from({ length: 30 }, (_, i) => {
  const qNum = i + 1;
  const order = 90 + qNum;
  const qId = 4000 + qNum;

  const data: Array<{
    q: string;
    a: string;
    b: string;
    c: string;
    d: string;
    ans: number;
  }> = [
    {
      q: 'Choose the correct sentence in the Present Perfect Continuous tense:',
      a: 'She is reading a novel since morning.',
      b: 'She has been reading a novel since morning.',
      c: 'She had read a novel since morning.',
      d: 'She was reading a novel for morning.',
      ans: 2,
    },
    {
      q: 'Identify the passive voice of: "The teacher evaluated the answer sheets."',
      a: 'The answer sheets are evaluated by the teacher.',
      b: 'The answer sheets were evaluated by the teacher.',
      c: 'The answer sheets had evaluated by the teacher.',
      d: 'The teacher was evaluating the answer sheets.',
      ans: 2,
    },
    {
      q: 'Choose the correct preposition: "He has been suffering _____ malaria for two days."',
      a: 'with',
      b: 'by',
      c: 'from',
      d: 'of',
      ans: 3,
    },
    {
      q: 'Select the synonym of the word "BENEVOLENT":',
      a: 'Cruel',
      b: 'Generous and kind',
      c: 'Greedy',
      d: 'Arrogant',
      ans: 2,
    },
    {
      q: 'Select the antonym of the word "TRANSPARENT":',
      a: 'Clear',
      b: 'Luminous',
      c: 'Opaque',
      d: 'Fragile',
      ans: 3,
    },
    {
      q: 'Choose the correctly spelled word:',
      a: 'Accomodation',
      b: 'Accommodation',
      c: 'Acommodation',
      d: 'Accomadation',
      ans: 2,
    },
    {
      q: '"Neither the teacher nor the students _____ present in the auditorium."',
      a: 'was',
      b: 'were',
      c: 'is',
      d: 'has been',
      ans: 2,
    },
    {
      q: 'Choose the correct indirect speech: He said, "I am writing a letter now."',
      a: 'He said that he was writing a letter then.',
      b: 'He said that I was writing a letter now.',
      c: 'He says that he is writing a letter then.',
      d: 'He asked if he wrote a letter then.',
      ans: 1,
    },
    {
      q: 'Identify the figure of speech in: "The wind whispered through the dark trees."',
      a: 'Simile',
      b: 'Metaphor',
      c: 'Personification',
      d: 'Hyperbole',
      ans: 3,
    },
    {
      q: 'Identify the figure of speech in: "As brave as a lion."',
      a: 'Simile',
      b: 'Metaphor',
      c: 'Oxymoron',
      d: 'Irony',
      ans: 1,
    },
    {
      q: 'Which method of English teaching emphasizes direct association between words and ideas without using the mother tongue?',
      a: 'Grammar-Translation Method',
      b: 'Direct Method (నేరుగా బోధించే పద్ధతి)',
      c: 'Bilingual Method',
      d: 'Structural Approach',
      ans: 2,
    },
    {
      q: 'In the Bilingual Method developed by Dr. C.J. Dodson, the mother tongue is used exclusively by:',
      a: 'Only the students',
      b: 'Only the teacher when explaining difficult concepts',
      c: 'Both students and parents at home only',
      d: 'Neither teacher nor students at any time',
      ans: 2,
    },
    {
      q: 'Phonetics is the scientific study of:',
      a: 'Sentence structures and syntax',
      b: 'Speech sounds and their production, transmission, and perception',
      c: 'Word origins and etymology',
      d: 'Punctuation and handwriting mechanics',
      ans: 2,
    },
    {
      q: 'How many total speech sounds (phonemes) are there in standard Received Pronunciation (RP) of the English language?',
      a: '26 phonemes',
      b: '44 phonemes (20 vowels + 24 consonants)',
      c: '48 phonemes',
      d: '52 phonemes',
      ans: 2,
    },
    {
      q: 'In the word "KNIFE", the silent letter is:',
      a: 'K',
      b: 'N',
      c: 'I',
      d: 'F',
      ans: 1,
    },
    {
      q: 'Choose the correct question tag: "She sings melodiously, _____?"',
      a: 'is she?',
      b: 'doesn\'t she?',
      c: 'didn\'t she?',
      d: 'hasn\'t she?',
      ans: 2,
    },
    {
      q: 'Choose the correct question tag: "They haven\'t finished the project, _____?"',
      a: 'have they?',
      b: 'haven\'t they?',
      c: 'did they?',
      d: 'are they?',
      ans: 1,
    },
    {
      q: 'Identify the type of clause underlined: "The boy *who won the first prize* is my cousin."',
      a: 'Adverb Clause of Time',
      b: 'Defining Adjective (Relative) Clause',
      c: 'Noun Clause as Object',
      d: 'Conditional Clause',
      ans: 2,
    },
    {
      q: 'Fill in the blank with the appropriate conditional verb: "If it rains, we _____ the picnic."',
      a: 'would cancel',
      b: 'will cancel (First Conditional: If + Present Simple, will + base verb)',
      c: 'would have cancelled',
      d: 'cancelled',
      ans: 2,
    },
    {
      q: 'Choose the appropriate idiom meaning "to face a difficult situation courageously":',
      a: 'Bite the bullet',
      b: 'Cry over spilt milk',
      c: 'Beat around the bush',
      d: 'Spill the beans',
      ans: 1,
    },
    {
      q: 'Choose the correct collective noun: "A _____ of wolves attacked the herd."',
      a: 'flock',
      b: 'pack',
      c: 'herd',
      d: 'pride',
      ans: 2,
    },
    {
      q: 'Choose the correct modal auxiliary for polite request: "_____ you please pass the salt?"',
      a: 'Must',
      b: 'Could / Would',
      c: 'Shall',
      d: 'Ought',
      ans: 2,
    },
    {
      q: 'Which of the following is a productive/expressive skill in English language learning?',
      a: 'Listening',
      b: 'Reading',
      c: 'Speaking and Writing',
      d: 'Silent comprehension',
      ans: 3,
    },
    {
      q: 'Which of the following are receptive skills in language acquisition?',
      a: 'Speaking and Writing',
      b: 'Listening and Reading',
      c: 'Writing and Translating',
      d: 'Grammar analysis and Spelling',
      ans: 2,
    },
    {
      q: 'Skimming a reading text means:',
      a: 'Reading word-by-word with a dictionary to find roots',
      b: 'Quickly reading through a text to get the general gist or main idea',
      c: 'Locating a specific single number or phone number (scanning)',
      d: 'Translating each sentence into the mother tongue',
      ans: 2,
    },
    {
      q: 'Scanning a text involves:',
      a: 'Reading rapidly to find specific pieces of information (like a date, name, or statistic)',
      b: 'Reading poems aloud with artistic rhythm',
      c: 'Memorizing the entire passage verbatim',
      d: 'Critiquing the moral philosophy of the author',
      ans: 1,
    },
    {
      q: 'For a child with hearing impairment in an inclusive classroom, the English teacher should primarily:',
      a: 'Speak loudly while facing the blackboard with back to students',
      b: 'Ensure clear lip visibility, face the student, and supplement with visual text aids and gestures',
      c: 'Excuse the student from all English vocabulary learning',
      d: 'Prohibit all visual materials to test hearing strictly',
      ans: 2,
    },
    {
      q: 'Choose the correct compound word formed by Noun + Noun:',
      a: 'Sunlight (Sun + Light)',
      b: 'Overcome',
      c: 'Whitewash',
      d: 'Undergo',
      ans: 1,
    },
    {
      q: 'Choose the word that is an adjective in the sentence: "The elderly gentleman donated generously."',
      a: 'gentleman',
      b: 'donated',
      c: 'elderly',
      d: 'generously',
      ans: 3,
    },
    {
      q: 'Remedial teaching in English is primarily intended for:',
      a: 'Gifted learners only to prepare them for Olympiads',
      b: 'Addressing specific learning gaps and misconceptions identified in diagnostic evaluation',
      c: 'Covering the syllabus ahead of scheduled board exams',
      d: 'Punishing students who missed regular classes',
      ans: 2,
    },
  ];

  const item = data[i];
  return {
    question_id: qId,
    subject: 'Language II (English)',
    question_number: qNum,
    question_order: order,
    question: item.q,
    option_a: item.a,
    option_b: item.b,
    option_c: item.c,
    option_d: item.d,
    correct_option: item.ans,
  };
});

export const PAPER_1A_QUESTIONS: TetQuestion[] = [
  ...cdpQuestions,
  ...mathQuestions,
  ...teluguQuestions,
  ...englishQuestions,
];

export const MOCK_TESTS_1A: TetTest[] = [
  PAPER_1A_TEST,
  {
    id: 'c97f31ea-1125-4ff7-84bc-000000000002',
    title: 'Special APTET Paper 1A Mock Test 02',
    description: 'Full-length 120-question mock examination for Special APTET Paper 1A (Classes I-V).',
    test_type: 'PAPER_1A_MOCK',
    duration_minutes: 150,
    total_questions: 120,
    created_at: '2026-10-05T12:05:00.000Z',
  },
  {
    id: 'c97f31ea-1125-4ff7-84bc-000000000003',
    title: 'Special APTET Paper 1A Mock Test 03',
    description: 'Full-length 120-question mock examination for Special APTET Paper 1A (Classes I-V).',
    test_type: 'PAPER_1A_MOCK',
    duration_minutes: 150,
    total_questions: 120,
    created_at: '2026-10-05T12:10:00.000Z',
  },
  {
    id: 'c97f31ea-1125-4ff7-84bc-000000000004',
    title: 'Special APTET Paper 1A Mock Test 04',
    description: 'Full-length 120-question mock examination for Special APTET Paper 1A (Classes I-V).',
    test_type: 'PAPER_1A_MOCK',
    duration_minutes: 150,
    total_questions: 120,
    created_at: '2026-10-05T12:15:00.000Z',
  },
  {
    id: 'c97f31ea-1125-4ff7-84bc-000000000005',
    title: 'Special APTET Paper 1A Mock Test 05',
    description: 'Full-length 120-question mock examination for Special APTET Paper 1A (Classes I-V).',
    test_type: 'PAPER_1A_MOCK',
    duration_minutes: 150,
    total_questions: 120,
    created_at: '2026-10-05T12:20:00.000Z',
  },
  {
    id: 'c97f31ea-1125-4ff7-84bc-000000000006',
    title: 'Special APTET Paper 1A Mock Test 06',
    description: 'Full-length 120-question mock examination for Special APTET Paper 1A (Classes I-V).',
    test_type: 'PAPER_1A_MOCK',
    duration_minutes: 150,
    total_questions: 120,
    created_at: '2026-10-05T12:25:00.000Z',
  },
  {
    id: 'c97f31ea-1125-4ff7-84bc-000000000007',
    title: 'Special APTET Paper 1A Mock Test 07',
    description: 'Full-length 120-question mock examination for Special APTET Paper 1A (Classes I-V).',
    test_type: 'PAPER_1A_MOCK',
    duration_minutes: 150,
    total_questions: 120,
    created_at: '2026-10-05T12:30:00.000Z',
  },
  {
    id: 'c97f31ea-1125-4ff7-84bc-000000000008',
    title: 'Special APTET Paper 1A Mock Test 08',
    description: 'Full-length 120-question mock examination for Special APTET Paper 1A (Classes I-V).',
    test_type: 'PAPER_1A_MOCK',
    duration_minutes: 150,
    total_questions: 120,
    created_at: '2026-10-05T12:35:00.000Z',
  },
  {
    id: 'c97f31ea-1125-4ff7-84bc-000000000009',
    title: 'Special APTET Paper 1A Mock Test 09',
    description: 'Full-length 120-question mock examination for Special APTET Paper 1A (Classes I-V).',
    test_type: 'PAPER_1A_MOCK',
    duration_minutes: 150,
    total_questions: 120,
    created_at: '2026-10-05T12:40:00.000Z',
  },
  {
    id: 'c97f31ea-1125-4ff7-84bc-000000000010',
    title: 'Special APTET Paper 1A Mock Test 10',
    description: 'Full-length 120-question mock examination for Special APTET Paper 1A (Classes I-V).',
    test_type: 'PAPER_1A_MOCK',
    duration_minutes: 150,
    total_questions: 120,
    created_at: '2026-10-05T12:45:00.000Z',
  },
];

function getPermutedSet(arr: TetQuestion[], testNum: number, startOrder: number): TetQuestion[] {
  const steps = [7, 11, 13, 17, 19, 23, 29, 31, 37];
  const step = steps[(testNum - 2) % steps.length];
  const offset = (testNum * 13) % arr.length;

  const result: TetQuestion[] = [];
  for (let i = 0; i < arr.length; i++) {
    const idx = (offset + i * step) % arr.length;
    const base = arr[idx];
    result.push({
      ...base,
      question_number: startOrder + i,
      question_order: startOrder + i,
    });
  }
  return result;
}

export function getMockTestWithQuestions(testId: string): TetTestWithQuestions | null {
  const foundTest = MOCK_TESTS_1A.find((t) => t.id === testId);
  if (!foundTest) {
    return null;
  }

  if (testId === PAPER_1A_TEST_ID) {
    return {
      test: foundTest,
      questions: PAPER_1A_QUESTIONS,
    };
  }

  // Derive test number from test id (e.g. ...0002 -> 2)
  const lastDigits = parseInt(testId.slice(-2), 10) || 2;
  const testNum = Math.min(Math.max(lastDigits, 2), 10);

  const cdp = getPermutedSet(cdpQuestions, testNum, 1);
  const math = getPermutedSet(mathQuestions, testNum, 31);
  const telugu = getPermutedSet(teluguQuestions, testNum, 61);
  const english = getPermutedSet(englishQuestions, testNum, 91);

  return {
    test: foundTest,
    questions: [...cdp, ...math, ...telugu, ...english],
  };
}

